sudo: required
services:
  - docker

before_install:
  - docker build -t saho87/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true saho87/react-test npm test

after_success:
  - docker build -t saho87/multi-client ./client
  - docker build -t saho87/multi-ngnix ./nginx
  - docker build -t saho87/multi-server ./server
  - docker build -t saho87/multi-worker ./worker

  # Log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #Take those images an push them to docker hub
  - docker push saho87/multi-client
  - docker push saho87/multi-nginx
  - docker push saho87/multi-server
  - docker push saho87/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-999217823059'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY 